package clases;
// Generated 31/10/2018 20:58:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clasificacion generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private int codigo;
     private String descripcion;
     private String nombreclasificacion;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);
     private Set<Historialclasificacion> historialclasificacions = new HashSet<Historialclasificacion>(0);
     private Set<Gruporesolucion> gruporesolucions = new HashSet<Gruporesolucion>(0);

    public Clasificacion() {
    }

	
    public Clasificacion(int codigo, String descripcion, String nombreclasificacion) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.nombreclasificacion = nombreclasificacion;
    }
    public Clasificacion(int codigo, String descripcion, String nombreclasificacion, Set<Ticket> tickets, Set<Historialclasificacion> historialclasificacions, Set<Gruporesolucion> gruporesolucions) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.nombreclasificacion = nombreclasificacion;
       this.tickets = tickets;
       this.historialclasificacions = historialclasificacions;
       this.gruporesolucions = gruporesolucions;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombreclasificacion() {
        return this.nombreclasificacion;
    }
    
    public void setNombreclasificacion(String nombreclasificacion) {
        this.nombreclasificacion = nombreclasificacion;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }
    public Set<Historialclasificacion> getHistorialclasificacions() {
        return this.historialclasificacions;
    }
    
    public void setHistorialclasificacions(Set<Historialclasificacion> historialclasificacions) {
        this.historialclasificacions = historialclasificacions;
    }
    public Set<Gruporesolucion> getGruporesolucions() {
        return this.gruporesolucions;
    }
    
    public void setGruporesolucions(Set<Gruporesolucion> gruporesolucions) {
        this.gruporesolucions = gruporesolucions;
    }




}


