package clases;
// Generated 06/12/2018 15:40:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int legajoEmpleado;
     private Gruporesolucion gruporesolucion;
     private Usuario usuario;
     private String email;
     private String nombre;
     private String apellido;
     private int telefonointerno;
     private int telefonodirecto;
     private String descripcioncargo;
     private String ubicacion;
     private Set tickets = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int legajoEmpleado, String email, String nombre, String apellido, int telefonointerno, int telefonodirecto, String descripcioncargo, String ubicacion) {
        this.legajoEmpleado = legajoEmpleado;
        this.email = email;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefonointerno = telefonointerno;
        this.telefonodirecto = telefonodirecto;
        this.descripcioncargo = descripcioncargo;
        this.ubicacion = ubicacion;
    }
    public Empleado(int legajoEmpleado, Gruporesolucion gruporesolucion, Usuario usuario, String email, String nombre, String apellido, int telefonointerno, int telefonodirecto, String descripcioncargo, String ubicacion, Set tickets) {
       this.legajoEmpleado = legajoEmpleado;
       this.gruporesolucion = gruporesolucion;
       this.usuario = usuario;
       this.email = email;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefonointerno = telefonointerno;
       this.telefonodirecto = telefonodirecto;
       this.descripcioncargo = descripcioncargo;
       this.ubicacion = ubicacion;
       this.tickets = tickets;
    }
   
    public int getLegajoEmpleado() {
        return this.legajoEmpleado;
    }
    
    public void setLegajoEmpleado(int legajoEmpleado) {
        this.legajoEmpleado = legajoEmpleado;
    }
    public Gruporesolucion getGruporesolucion() {
        return this.gruporesolucion;
    }
    
    public void setGruporesolucion(Gruporesolucion gruporesolucion) {
        this.gruporesolucion = gruporesolucion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getTelefonointerno() {
        return this.telefonointerno;
    }
    
    public void setTelefonointerno(int telefonointerno) {
        this.telefonointerno = telefonointerno;
    }
    public int getTelefonodirecto() {
        return this.telefonodirecto;
    }
    
    public void setTelefonodirecto(int telefonodirecto) {
        this.telefonodirecto = telefonodirecto;
    }
    public String getDescripcioncargo() {
        return this.descripcioncargo;
    }
    
    public void setDescripcioncargo(String descripcioncargo) {
        this.descripcioncargo = descripcioncargo;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


