package clases;
// Generated 31/10/2018 16:09:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Gruporesolucion generated by hbm2java
 */
public class Gruporesolucion  implements java.io.Serializable {


     private int codigoGrupoResolucion;
     private String nombregrupo;
     private Set<Intervencion> intervencions = new HashSet<Intervencion>(0);
     private Set<Clasificacion> clasificacions = new HashSet<Clasificacion>(0);

    public Gruporesolucion() {
    }

	
    public Gruporesolucion(int codigoGrupoResolucion, String nombregrupo) {
        this.codigoGrupoResolucion = codigoGrupoResolucion;
        this.nombregrupo = nombregrupo;
    }
    public Gruporesolucion(int codigoGrupoResolucion, String nombregrupo, Set<Intervencion> intervencions, Set<Clasificacion> clasificacions) {
       this.codigoGrupoResolucion = codigoGrupoResolucion;
       this.nombregrupo = nombregrupo;
       this.intervencions = intervencions;
       this.clasificacions = clasificacions;
    }
   
    public int getCodigoGrupoResolucion() {
        return this.codigoGrupoResolucion;
    }
    
    public void setCodigoGrupoResolucion(int codigoGrupoResolucion) {
        this.codigoGrupoResolucion = codigoGrupoResolucion;
    }
    public String getNombregrupo() {
        return this.nombregrupo;
    }
    
    public void setNombregrupo(String nombregrupo) {
        this.nombregrupo = nombregrupo;
    }
    public Set<Intervencion> getIntervencions() {
        return this.intervencions;
    }
    
    public void setIntervencions(Set<Intervencion> intervencions) {
        this.intervencions = intervencions;
    }
    public Set<Clasificacion> getClasificacions() {
        return this.clasificacions;
    }
    
    public void setClasificacions(Set<Clasificacion> clasificacions) {
        this.clasificacions = clasificacions;
    }




}


