package clases;
// Generated 31/10/2018 16:09:15 by Hibernate Tools 4.3.1



/**
 * HistorialclasificacionId generated by hbm2java
 */
public class HistorialclasificacionId  implements java.io.Serializable {


     private int nroTicket;
     private int codigoClasificacion;
     private int legajoEmpleado;

    public HistorialclasificacionId() {
    }

    public HistorialclasificacionId(int nroTicket, int codigoClasificacion, int legajoEmpleado) {
       this.nroTicket = nroTicket;
       this.codigoClasificacion = codigoClasificacion;
       this.legajoEmpleado = legajoEmpleado;
    }
   
    public int getNroTicket() {
        return this.nroTicket;
    }
    
    public void setNroTicket(int nroTicket) {
        this.nroTicket = nroTicket;
    }
    public int getCodigoClasificacion() {
        return this.codigoClasificacion;
    }
    
    public void setCodigoClasificacion(int codigoClasificacion) {
        this.codigoClasificacion = codigoClasificacion;
    }
    public int getLegajoEmpleado() {
        return this.legajoEmpleado;
    }
    
    public void setLegajoEmpleado(int legajoEmpleado) {
        this.legajoEmpleado = legajoEmpleado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistorialclasificacionId) ) return false;
		 HistorialclasificacionId castOther = ( HistorialclasificacionId ) other; 
         
		 return (this.getNroTicket()==castOther.getNroTicket())
 && (this.getCodigoClasificacion()==castOther.getCodigoClasificacion())
 && (this.getLegajoEmpleado()==castOther.getLegajoEmpleado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroTicket();
         result = 37 * result + this.getCodigoClasificacion();
         result = 37 * result + this.getLegajoEmpleado();
         return result;
   }   


}


