package clases;
// Generated 26/10/2018 19:27:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historialclasificacion generated by hbm2java
 */
public class Historialclasificacion  implements java.io.Serializable {


     private HistorialclasificacionId id;
     private Clasificacion clasificacion;
     private Empleado empleado;
     private Date fechainicio;
     private Date fechafin;
     private Date horainicio;
     private Date horafin;

    public Historialclasificacion() {
    }

    public Historialclasificacion(HistorialclasificacionId id, Clasificacion clasificacion, Empleado empleado, Date fechainicio, Date fechafin, Date horainicio, Date horafin) {
       this.id = id;
       this.clasificacion = clasificacion;
       this.empleado = empleado;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.horainicio = horainicio;
       this.horafin = horafin;
    }
   
    public HistorialclasificacionId getId() {
        return this.id;
    }
    
    public void setId(HistorialclasificacionId id) {
        this.id = id;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }




}


