package clases;
// Generated 26/10/2018 19:27:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int nroTicket;
     private Clasificacion clasificacion;
     private Empleado empleado;
     private Ticket ticket;
     private Date fecahapertura;
     private String estadoactual;
     private Date horaapertura;
     private String descripcion;
     private Set observacions = new HashSet(0);
     private Set historialtickets = new HashSet(0);
     private Set intervencions = new HashSet(0);
//    private Ticket ticket;

    public Ticket() {
    }

	
    public Ticket(Clasificacion clasificacion, Empleado empleado, Ticket ticket, Date fecahapertura, String estadoactual, Date horaapertura) {
        this.clasificacion = clasificacion;
        this.empleado = empleado;
        this.ticket = ticket;
        this.fecahapertura = fecahapertura;
        this.estadoactual = estadoactual;
        this.horaapertura = horaapertura;
    }
    public Ticket(Clasificacion clasificacion, Empleado empleado, Ticket ticket, Date fecahapertura, String estadoactual, Date horaapertura, String descripcion, Set observacions, Set historialtickets, Set intervencions) {
       this.clasificacion = clasificacion;
       this.empleado = empleado;
       this.ticket = ticket;
       this.fecahapertura = fecahapertura;
       this.estadoactual = estadoactual;
       this.horaapertura = horaapertura;
       this.descripcion = descripcion;
       this.observacions = observacions;
       this.historialtickets = historialtickets;
       this.intervencions = intervencions;
       //this.ticket = ticket;
    }
   
    public int getNroTicket() {
        return this.nroTicket;
    }
    
    public void setNroTicket(int nroTicket) {
        this.nroTicket = nroTicket;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public Date getFecahapertura() {
        return this.fecahapertura;
    }
    
    public void setFecahapertura(Date fecahapertura) {
        this.fecahapertura = fecahapertura;
    }
    public String getEstadoactual() {
        return this.estadoactual;
    }
    
    public void setEstadoactual(String estadoactual) {
        this.estadoactual = estadoactual;
    }
    public Date getHoraapertura() {
        return this.horaapertura;
    }
    
    public void setHoraapertura(Date horaapertura) {
        this.horaapertura = horaapertura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getObservacions() {
        return this.observacions;
    }
    
    public void setObservacions(Set observacions) {
        this.observacions = observacions;
    }
    public Set getHistorialtickets() {
        return this.historialtickets;
    }
    
    public void setHistorialtickets(Set historialtickets) {
        this.historialtickets = historialtickets;
    }
    public Set getIntervencions() {
        return this.intervencions;
    }
    
    public void setIntervencions(Set intervencions) {
        this.intervencions = intervencions;
    }
/*    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

*/


}


