package clases;
// Generated 23/11/2018 20:16:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int nroTicket;
     private Clasificacion clasificacion;
     private Empleado empleado;
     private Date fecahapertura;
     private String estadoactual;
     private Date horaapertura;
     private String descripcion;
     private Set historialclasificacions = new HashSet(0);
     private Set historialtickets = new HashSet(0);
     private Set intervencions = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(int nroTicket, Clasificacion clasificacion, Empleado empleado, Date fecahapertura, String estadoactual, Date horaapertura) {
        this.nroTicket = nroTicket;
        this.clasificacion = clasificacion;
        this.empleado = empleado;
        this.fecahapertura = fecahapertura;
        this.estadoactual = estadoactual;
        this.horaapertura = horaapertura;
    }
    public Ticket(int nroTicket, Clasificacion clasificacion, Empleado empleado, Date fecahapertura, String estadoactual, Date horaapertura, String descripcion, Set historialclasificacions, Set historialtickets, Set intervencions) {
       this.nroTicket = nroTicket;
       this.clasificacion = clasificacion;
       this.empleado = empleado;
       this.fecahapertura = fecahapertura;
       this.estadoactual = estadoactual;
       this.horaapertura = horaapertura;
       this.descripcion = descripcion;
       this.historialclasificacions = historialclasificacions;
       this.historialtickets = historialtickets;
       this.intervencions = intervencions;
    }
   
    public int getNroTicket() {
        return this.nroTicket;
    }
    
    public void setNroTicket(int nroTicket) {
        this.nroTicket = nroTicket;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecahapertura() {
        return this.fecahapertura;
    }
    
    public void setFecahapertura(Date fecahapertura) {
        this.fecahapertura = fecahapertura;
    }
    public String getEstadoactual() {
        return this.estadoactual;
    }
    
    public void setEstadoactual(String estadoactual) {
        this.estadoactual = estadoactual;
    }
    public Date getHoraapertura() {
        return this.horaapertura;
    }
    
    public void setHoraapertura(Date horaapertura) {
        this.horaapertura = horaapertura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getHistorialclasificacions() {
        return this.historialclasificacions;
    }
    
    public void setHistorialclasificacions(Set historialclasificacions) {
        this.historialclasificacions = historialclasificacions;
    }
    public Set getHistorialtickets() {
        return this.historialtickets;
    }
    
    public void setHistorialtickets(Set historialtickets) {
        this.historialtickets = historialtickets;
    }
    public Set getIntervencions() {
        return this.intervencions;
    }
    
    public void setIntervencions(Set intervencions) {
        this.intervencions = intervencions;
    }




}


