package clases;
// Generated 14/11/2018 14:32:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int legajoUsuario;
     private String tipo;
     private Set historialclasificacions = new HashSet(0);
     private Set empleados = new HashSet(0);
     private Set historialtickets = new HashSet(0);
     private Set historialintervencions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int legajoUsuario, String tipo) {
        this.legajoUsuario = legajoUsuario;
        this.tipo = tipo;
    }
    public Usuario(int legajoUsuario, String tipo, Set historialclasificacions, Set empleados, Set historialtickets, Set historialintervencions) {
       this.legajoUsuario = legajoUsuario;
       this.tipo = tipo;
       this.historialclasificacions = historialclasificacions;
       this.empleados = empleados;
       this.historialtickets = historialtickets;
       this.historialintervencions = historialintervencions;
    }
   
    public int getLegajoUsuario() {
        return this.legajoUsuario;
    }
    
    public void setLegajoUsuario(int legajoUsuario) {
        this.legajoUsuario = legajoUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getHistorialclasificacions() {
        return this.historialclasificacions;
    }
    
    public void setHistorialclasificacions(Set historialclasificacions) {
        this.historialclasificacions = historialclasificacions;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getHistorialtickets() {
        return this.historialtickets;
    }
    
    public void setHistorialtickets(Set historialtickets) {
        this.historialtickets = historialtickets;
    }
    public Set getHistorialintervencions() {
        return this.historialintervencions;
    }
    
    public void setHistorialintervencions(Set historialintervencions) {
        this.historialintervencions = historialintervencions;
    }




}


