
package Ventanas;

import Dao.GrupoResolucionDao;
import clases.Clasificacion;
import clases.Gruporesolucion;
import clases.Historialclasificacion;
import clases.Historialticket;
import clases.Ticket;
import clases.TicketDTO;
import controllers.Enum_EstadoTicket;
import controllers.GestorClasificacion;
import controllers.GestorGrupoResolucion;
import controllers.GestorTicket;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javafx.scene.input.KeyCode;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import org.jdesktop.swingx.decorator.EnabledHighlighter;

/**
 *
 * @author Marcos
 */
public class Caso_de_uso_04 extends javax.swing.JFrame {

    private VerDetalleTicket ver_detalle_ticket;
    private Ticket ticket;
    
    public Caso_de_uso_04() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
        cerrar();
        
        jButton1Cancelar.requestFocus();
        //jComboBoxGrupoResolucion.setEnabled(false);
        jTextFieldDescripcion.setLineWrap(true); // evita expansion en ancho del textArea
        jTextAreaObservacion.setLineWrap(true); // evita expansion en ancho del textArea
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEstadoActual = new javax.swing.JLabel();
        jLabelNuevoEstado = new javax.swing.JLabel();
        jLabelClasificacionTicket = new javax.swing.JLabel();
        jLabelGrupoResolucion = new javax.swing.JLabel();
        jLabelObservacion = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jComboBoxClasificacion = new javax.swing.JComboBox<>();
        jComboBoxGrupoResolucion = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldDescripcion = new javax.swing.JTextArea();
        jButton1Confirmar = new javax.swing.JButton();
        jButton1Cancelar = new javax.swing.JButton();
        jLabel1NroTicket = new javax.swing.JLabel();
        jTextField3NroTicketPorPantalla = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Derivar ticket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstadoActual.setBackground(new java.awt.Color(191, 185, 185));
        jLabelEstadoActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstadoActual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoActual.setText("Estado Actual Del Ticket:");
        getContentPane().add(jLabelEstadoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelNuevoEstado.setBackground(new java.awt.Color(191, 185, 185));
        jLabelNuevoEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNuevoEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuevoEstado.setText("Nuevo Estado Del Ticket:");
        getContentPane().add(jLabelNuevoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabelClasificacionTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabelClasificacionTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClasificacionTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasificacionTicket.setText("Clasificacion Del Ticket:");
        getContentPane().add(jLabelClasificacionTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabelGrupoResolucion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGrupoResolucion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrupoResolucion.setText("Grupo De Resolucion:");
        getContentPane().add(jLabelGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabelObservacion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelObservacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelObservacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacion.setText("Observaciones:");
        getContentPane().add(jLabelObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabelDescripcion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripcion Del Problema:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextFieldEstado.setEditable(false);
        jTextFieldEstado.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldEstado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEstado.setFocusable(false);
        getContentPane().add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 240, 30));

        jComboBoxClasificacion.setBackground(new java.awt.Color(191, 185, 185));
        jComboBoxClasificacion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxClasificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxClasificacionFocusGained(evt);
            }
        });
        jComboBoxClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 560, 30));

        jComboBoxGrupoResolucion.setBackground(new java.awt.Color(191, 185, 185));
        jComboBoxGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxGrupoResolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(jComboBoxGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 560, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(191, 185, 185));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.setText("Abierto derivado");
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 220, 30));

        jTextAreaObservacion.setBackground(new java.awt.Color(245, 245, 245));
        jTextAreaObservacion.setColumns(20);
        jTextAreaObservacion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaObservacion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 720, 120));

        jTextFieldDescripcion.setEditable(false);
        jTextFieldDescripcion.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldDescripcion.setColumns(20);
        jTextFieldDescripcion.setRows(5);
        jTextFieldDescripcion.setFocusable(false);
        jScrollPane2.setViewportView(jTextFieldDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 720, 120));

        jButton1Confirmar.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1Confirmar.setText("Confirmar");
        jButton1Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConfirmarActionPerformed(evt);
            }
        });
        jButton1Confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1ConfirmarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton1Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 120, 40));

        jButton1Cancelar.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1Cancelar.setText("Cancelar");
        jButton1Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CancelarActionPerformed(evt);
            }
        });
        jButton1Cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1CancelarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton1Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 120, 40));

        jLabel1NroTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1NroTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1NroTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1NroTicket.setText("Nro. Ticket:");
        getContentPane().add(jLabel1NroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField3NroTicketPorPantalla.setEditable(false);
        jTextField3NroTicketPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextField3NroTicketPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3NroTicketPorPantalla.setFocusable(false);
        getContentPane().add(jTextField3NroTicketPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 240, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCU1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 635));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxClasificacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxClasificacionFocusGained
                    jComboBoxClasificacion.showPopup();
    }//GEN-LAST:event_jComboBoxClasificacionFocusGained

    private void jButton1CancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1CancelarKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1Cancelar.doClick();
        } 
    }//GEN-LAST:event_jButton1CancelarKeyPressed

    private void jButton1CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CancelarActionPerformed
        salir();
    }//GEN-LAST:event_jButton1CancelarActionPerformed

    private void jComboBoxClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClasificacionActionPerformed
        cargarComboGrupo(jComboBoxClasificacion.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxClasificacionActionPerformed

    private void jButton1ConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1ConfirmarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1Confirmar.doClick();
        } 
    }//GEN-LAST:event_jButton1ConfirmarKeyPressed

    private void jButton1ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConfirmarActionPerformed
       if(jTextAreaObservacion.getText().isEmpty()){
          
           JOptionPane.showMessageDialog(null, "El campo de observacion no puede estar vacío");
       }else{
            GestorTicket gt = new GestorTicket();
            String nuevoEstado = Enum_EstadoTicket.ABIERTO_DERIVADO.toString(),
                   observacion = jTextAreaObservacion.getText(),
                   nuevaClasificacion = jComboBoxClasificacion.getSelectedItem().toString(),
                   grupoResolucion = jComboBoxGrupoResolucion.getSelectedItem().toString();
            
                              
            gt.derivarTicket(ticket, nuevoEstado, observacion, nuevaClasificacion, nuevoEstado);
       }
                
        
    }//GEN-LAST:event_jButton1ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Cancelar;
    private javax.swing.JButton jButton1Confirmar;
    private javax.swing.JComboBox<String> jComboBoxClasificacion;
    private javax.swing.JComboBox<String> jComboBoxGrupoResolucion;
    private javax.swing.JLabel jLabel1NroTicket;
    private javax.swing.JLabel jLabelClasificacionTicket;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelEstadoActual;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGrupoResolucion;
    private javax.swing.JLabel jLabelNuevoEstado;
    private javax.swing.JLabel jLabelObservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaObservacion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3NroTicketPorPantalla;
    private javax.swing.JTextArea jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEstado;
    // End of variables declaration//GEN-END:variables

public void cerrar(){
        
        try{
            this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                    public void windowClosing(WindowEvent e){
                    salir();
                }
               
            });
        
        }catch(Exception e){
                e.printStackTrace();
                }
    }
    public void salir(){
            
        int valor=JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir? Se perderán los cambios realizados","Advertencia",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(valor==JOptionPane.YES_OPTION){
                       
            this.setVisible(false);
            ver_detalle_ticket.setVisible(true);
        }
    }

    public void derivarTicket(Ticket ticket, VerDetalleTicket detalle) {
        ver_detalle_ticket = detalle;
        this.ticket = ticket;
        this.cargarCampos(ticket);
    }

    private void cargarCampos(Ticket ticket) {
        
        GestorClasificacion gestorClasificacion = new GestorClasificacion();
        GestorTicket gestorTicket = new GestorTicket();
        List<String> clasificaciones = new ArrayList<>();
        Historialticket historialTicket = gestorTicket.obtenerHistorialTicket(ticket, ticket.getEstadoactual());
        clasificaciones=gestorClasificacion.obtenerNombresClasificaciones();
        DefaultComboBoxModel comboClasificacion= new DefaultComboBoxModel();
        
        
        
        comboClasificacion.addElement(ticket.getClasificacion().getNombreclasificacion());
        for(int i=0; i<clasificaciones.size(); i++){
            if(!clasificaciones.get(i).equals(ticket.getClasificacion().getNombreclasificacion())){
                    comboClasificacion.addElement(clasificaciones.get(i));
            }
            
        }
        
        jComboBoxClasificacion.setModel(comboClasificacion);       
        jTextField3NroTicketPorPantalla.setText(String.valueOf(ticket.getNroTicket()));
        jTextFieldEstado.setText(ticket.getEstadoactual());
        jTextFieldDescripcion.setText(ticket.getDescripcion());
        cargarComboGrupo(jComboBoxClasificacion.getSelectedItem().toString());
        
        
    }

    private void cargarComboGrupo(String clasificacionDelCombo){
                
        GestorGrupoResolucion gestorGrupo = new GestorGrupoResolucion();
        GestorClasificacion gestorClasificacion = new GestorClasificacion();
        List<Clasificacion> clasificaciones = new ArrayList<>();       
        List<Gruporesolucion> grupos = new ArrayList<>();
        DefaultComboBoxModel comboGrupo= new DefaultComboBoxModel();
         
        int i=0;
        
        clasificaciones = gestorClasificacion.obtenerClasificaciones();
        grupos = gestorGrupo.obtenerGrupos();
        
        while(!clasificaciones.get(i).getNombreclasificacion().equals(clasificacionDelCombo) && i<clasificaciones.size() ){
                i++;               
            }
        //casteo el set de grupoResolucions a arrayList
        Set clasificacionParaElGrupo = (Set) clasificaciones.get(i).getGruporesolucions();
        List<Gruporesolucion> list = new ArrayList<>(clasificacionParaElGrupo);
        
        for(int j=0; j<list.size(); j++){
            comboGrupo.addElement(list.get(j).getNombregrupo());
        }
       jComboBoxGrupoResolucion.setModel(comboGrupo);
    }
}