/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class caso_de_uso_11_visualizacion extends javax.swing.JFrame {

    /**
     * Creates new form caso_de_uso_11_visualizacion
     */
    public caso_de_uso_11_visualizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelCantidadDeTicketsAbiertos = new javax.swing.JLabel();
        jLabelCantidadDeTicketsCerrados = new javax.swing.JLabel();
        jTextFieldCantidadDeTicketsCerrados = new javax.swing.JTextField();
        jTextFieldCantidadDeTicketsAbiertos = new javax.swing.JTextField();
        jLabelLogoFondo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("visualización");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro. de ticket", "Legajo del usuario", "Apellido y nombre", "Teléfono interno", "Teléfono directo", "Fecha de derivación", "Hora de derivación", "Estado de la intervención"
            }
        ));
        jScrollPaneTabla.setViewportView(jTable1);

        getContentPane().add(jScrollPaneTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1010, 130));

        jLabelCantidadDeTicketsAbiertos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadDeTicketsAbiertos.setText("Cantidad de tickets abiertos:");
        getContentPane().add(jLabelCantidadDeTicketsAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabelCantidadDeTicketsCerrados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadDeTicketsCerrados.setText("Cantidad de tickets cerrados:");
        getContentPane().add(jLabelCantidadDeTicketsCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTextFieldCantidadDeTicketsCerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeTicketsCerradosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadDeTicketsCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, 30));

        jTextFieldCantidadDeTicketsAbiertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeTicketsAbiertosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadDeTicketsAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, 30));

        jLabelLogoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logofondo_GrupoResolucion.png"))); // NOI18N
        getContentPane().add(jLabelLogoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 350, 400));

        jLabelTitulo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTitulo.setFont(new java.awt.Font("MS PGothic", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(45, 93, 165));
        jLabelTitulo.setText("La llamita");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 200, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-grupoResolucion.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadDeTicketsCerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeTicketsCerradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeTicketsCerradosActionPerformed

    private void jTextFieldCantidadDeTicketsAbiertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeTicketsAbiertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeTicketsAbiertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caso_de_uso_11_visualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caso_de_uso_11_visualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caso_de_uso_11_visualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caso_de_uso_11_visualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caso_de_uso_11_visualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCantidadDeTicketsAbiertos;
    private javax.swing.JLabel jLabelCantidadDeTicketsCerrados;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantidadDeTicketsAbiertos;
    private javax.swing.JTextField jTextFieldCantidadDeTicketsCerrados;
    // End of variables declaration//GEN-END:variables
}
