
package Ventanas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class Caso_de_uso_05 extends javax.swing.JFrame {

    /**
     * Creates new form CasoDeUso05
     */
    public Caso_de_uso_05() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgruparPor = new javax.swing.JLabel();
        jComboBoxAgruparPor = new javax.swing.JComboBox<>();
        jLabelOrdenar = new javax.swing.JLabel();
        jComboBoxOrdenar = new javax.swing.JComboBox<>();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar reporte");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAgruparPor.setBackground(new java.awt.Color(191, 185, 185));
        jLabelAgruparPor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAgruparPor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgruparPor.setText("Agrupar por: ");
        getContentPane().add(jLabelAgruparPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jComboBoxAgruparPor.setBackground(new java.awt.Color(191, 185, 185));
        jComboBoxAgruparPor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxAgruparPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nro. Ticket", "Legajo", "Estado actual del ticket", "Ultimo grupo de resolucion", "Clasificacion actual del ticket" }));
        getContentPane().add(jComboBoxAgruparPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 400, 40));

        jLabelOrdenar.setBackground(new java.awt.Color(191, 185, 185));
        jLabelOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrdenar.setText("Ordenar: ");
        getContentPane().add(jLabelOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jComboBoxOrdenar.setBackground(new java.awt.Color(191, 185, 185));
        jComboBoxOrdenar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendentemente", "Descendentemente" }));
        getContentPane().add(jComboBoxOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 40));

        jButtonImprimir.setBackground(new java.awt.Color(191, 185, 185));
        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jButtonImprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonImprimirKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 120, 40));

        jButtonCancelar.setBackground(new java.awt.Color(191, 185, 185));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 120, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCU1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, 635));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       
        Caso_de_uso_02 a = new Caso_de_uso_02();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        JOptionPane.showMessageDialog(null, "Funcionalidad en desarrollo");
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelarKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonCancelar.doClick();
        } 
    }//GEN-LAST:event_jButtonCancelarKeyPressed

    private void jButtonImprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonImprimirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButtonImprimir.doClick();
        } 
    }//GEN-LAST:event_jButtonImprimirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JComboBox<String> jComboBoxAgruparPor;
    private javax.swing.JComboBox<String> jComboBoxOrdenar;
    private javax.swing.JLabel jLabelAgruparPor;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelOrdenar;
    // End of variables declaration//GEN-END:variables
}
