/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Marcos
 */
public class Caso_de_uso_23 extends javax.swing.JFrame {

    /**
     * Creates new form CasoDeUso23
     */
    public Caso_de_uso_23() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpciones = new javax.swing.JLabel();
        jLabelFiltrosUtilizados = new javax.swing.JLabel();
        jLabelOrdenado = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonAnterior = new javax.swing.JButton();
        jLabelVisualizando = new javax.swing.JLabel();
        jLabelUNO = new javax.swing.JLabel();
        jLabelDE = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombreGrupoResol = new javax.swing.JLabel();
        jLabelGrafico = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1UNO = new javax.swing.JLabel();
        jLabel1De = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jButton1Anterior = new javax.swing.JButton();
        jButton1Siguiente = new javax.swing.JButton();
        jLabelNroTicket = new javax.swing.JLabel();
        jLabelClasificacionActual = new javax.swing.JLabel();
        jLabelEstadoTicket = new javax.swing.JLabel();
        jLabelFechaApertura = new javax.swing.JLabel();
        jLabelEstadoIntervencion = new javax.swing.JLabel();
        jLabelTiempoRealAtencion = new javax.swing.JLabel();
        jLabelTiempoTotalAsig = new javax.swing.JLabel();
        jLabelObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabelInfoDelGrupoResolucion = new javax.swing.JLabel();
        jLabelInfoDelTicketAsociadoAlGrupo = new javax.swing.JLabel();
        jTextFieldNombreGrupoResolución = new javax.swing.JTextField();
        jTextFieldNroTicket = new javax.swing.JTextField();
        jTextFieldClasificaciónTicket = new javax.swing.JTextField();
        jTextFieldEstadoActualTicket = new javax.swing.JTextField();
        jTextFieldFechaApertura = new javax.swing.JTextField();
        jTextFieldEstadoIntervencion = new javax.swing.JTextField();
        jTextFieldTiempoAtencion = new javax.swing.JTextField();
        jTextFieldTiempoTotalAsignado = new javax.swing.JTextField();
        jLabelCantTicketAsociadosAlGrupo = new javax.swing.JLabel();
        jLabelConstanteC = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información por último grupo de resolución");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOpciones.setBackground(new java.awt.Color(191, 185, 185));
        jLabelOpciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpciones.setText("Opciones de ordenamiento ");
        getContentPane().add(jLabelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabelFiltrosUtilizados.setBackground(new java.awt.Color(191, 185, 185));
        jLabelFiltrosUtilizados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFiltrosUtilizados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiltrosUtilizados.setText("Filtros utilizados");
        getContentPane().add(jLabelFiltrosUtilizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 30));

        jLabelOrdenado.setBackground(new java.awt.Color(191, 185, 185));
        jLabelOrdenado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOrdenado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrdenado.setText("Ordenado");
        getContentPane().add(jLabelOrdenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(191, 185, 185));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 270, 30));

        jButtonAnterior.setBackground(new java.awt.Color(191, 185, 185));
        jButtonAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAnterior.setText("Anterior");
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabelVisualizando.setBackground(new java.awt.Color(191, 185, 185));
        jLabelVisualizando.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVisualizando.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVisualizando.setText("Visualizando");
        getContentPane().add(jLabelVisualizando, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 30));

        jLabelUNO.setBackground(new java.awt.Color(191, 185, 185));
        jLabelUNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUNO.setForeground(new java.awt.Color(51, 153, 255));
        jLabelUNO.setText("1");
        getContentPane().add(jLabelUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, 50));

        jLabelDE.setBackground(new java.awt.Color(191, 185, 185));
        jLabelDE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDE.setText("de");
        getContentPane().add(jLabelDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 30));

        jLabelX.setBackground(new java.awt.Color(191, 185, 185));
        jLabelX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelX.setForeground(new java.awt.Color(51, 153, 255));
        jLabelX.setText("X");
        getContentPane().add(jLabelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 50));

        jButtonSiguiente.setBackground(new java.awt.Color(191, 185, 185));
        jButtonSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1060, 10));

        jLabelNombreGrupoResol.setBackground(new java.awt.Color(191, 185, 185));
        jLabelNombreGrupoResol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombreGrupoResol.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreGrupoResol.setText("Nombre del grupo de resolución");
        getContentPane().add(jLabelNombreGrupoResol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabelGrafico.setBackground(new java.awt.Color(191, 185, 185));
        jLabelGrafico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGrafico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrafico.setText("Gráfico");
        getContentPane().add(jLabelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        panel1.setBackground(new java.awt.Color(191, 185, 185));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 300, 230));

        jLabel1UNO.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1UNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1UNO.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1UNO.setText("1");
        getContentPane().add(jLabel1UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, 40));

        jLabel1De.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1De.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1De.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1De.setText("de");
        getContentPane().add(jLabel1De, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, -1, 40));

        jLabelC.setBackground(new java.awt.Color(191, 185, 185));
        jLabelC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(51, 153, 255));
        jLabelC.setText("C");
        getContentPane().add(jLabelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 20, 40));

        jButton1Anterior.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Anterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1Anterior.setText("Anterior");
        jButton1Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        jButton1Siguiente.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Siguiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1Siguiente.setText("Siguiente");
        getContentPane().add(jButton1Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        jLabelNroTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabelNroTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNroTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNroTicket.setText("Nro. Ticket");
        getContentPane().add(jLabelNroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabelClasificacionActual.setBackground(new java.awt.Color(191, 185, 185));
        jLabelClasificacionActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClasificacionActual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasificacionActual.setText("Clasificación actual del ticket");
        getContentPane().add(jLabelClasificacionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabelEstadoTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabelEstadoTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstadoTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoTicket.setText("Estado actual del ticket");
        getContentPane().add(jLabelEstadoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabelFechaApertura.setBackground(new java.awt.Color(191, 185, 185));
        jLabelFechaApertura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaApertura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaApertura.setText("Fecha de apertura");
        getContentPane().add(jLabelFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jLabelEstadoIntervencion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelEstadoIntervencion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstadoIntervencion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoIntervencion.setText("Estado de la intervención");
        getContentPane().add(jLabelEstadoIntervencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 200, -1));

        jLabelTiempoRealAtencion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTiempoRealAtencion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTiempoRealAtencion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiempoRealAtencion.setText("Tiempo real de atención");
        getContentPane().add(jLabelTiempoRealAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        jLabelTiempoTotalAsig.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTiempoTotalAsig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTiempoTotalAsig.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiempoTotalAsig.setText("Tiempo total asignado");
        getContentPane().add(jLabelTiempoTotalAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        jLabelObservaciones.setBackground(new java.awt.Color(191, 185, 185));
        jLabelObservaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservaciones.setText("Observaciones");
        getContentPane().add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(191, 185, 185));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 320, 70));

        jButtonImprimir.setBackground(new java.awt.Color(191, 185, 185));
        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 120, 40));

        jButtonCerrar.setBackground(new java.awt.Color(191, 185, 185));
        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCerrar.setText("Cerrar");
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 120, 40));

        jTable1.setBackground(new java.awt.Color(191, 185, 185));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nro. Ticket"},
                {"Clasificación actual del ticket"},
                {"Estado actual del ticket"},
                {"Fecha de apertura"}
            },
            new String [] {
                "Ordenamiento por defecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(75, 102));
        jTable1.setRowHeight(17);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 250, 100));

        jTable2.setBackground(new java.awt.Color(191, 185, 185));
        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 - NULL"},
                {"2 - NULL"},
                {"3 - NULL"},
                {"4 - NULL"}
            },
            new String [] {
                "Nuevo ordenamiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(75, 102));
        jTable2.setRowHeight(17);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 250, 100));

        jTable3.setBackground(new java.awt.Color(191, 185, 185));
        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Filtro", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setPreferredSize(new java.awt.Dimension(160, 151));
        jTable3.setRowHeight(23);
        jScrollPane4.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, 50));

        jLabelInfoDelGrupoResolucion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelInfoDelGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInfoDelGrupoResolucion.setForeground(new java.awt.Color(246, 58, 58));
        jLabelInfoDelGrupoResolucion.setText("Información asociada al grupo de resolución:");
        getContentPane().add(jLabelInfoDelGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabelInfoDelTicketAsociadoAlGrupo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelInfoDelTicketAsociadoAlGrupo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInfoDelTicketAsociadoAlGrupo.setForeground(new java.awt.Color(246, 58, 58));
        jLabelInfoDelTicketAsociadoAlGrupo.setText("Información del ticket asociado al grupo de resolución:");
        getContentPane().add(jLabelInfoDelTicketAsociadoAlGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jTextFieldNombreGrupoResolución.setEditable(false);
        jTextFieldNombreGrupoResolución.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldNombreGrupoResolución.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNombreGrupoResolución, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 210, -1));

        jTextFieldNroTicket.setEditable(false);
        jTextFieldNroTicket.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldNroTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 210, -1));

        jTextFieldClasificaciónTicket.setEditable(false);
        jTextFieldClasificaciónTicket.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldClasificaciónTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldClasificaciónTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 210, -1));

        jTextFieldEstadoActualTicket.setEditable(false);
        jTextFieldEstadoActualTicket.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldEstadoActualTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldEstadoActualTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 210, -1));

        jTextFieldFechaApertura.setEditable(false);
        jTextFieldFechaApertura.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldFechaApertura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 210, -1));

        jTextFieldEstadoIntervencion.setEditable(false);
        jTextFieldEstadoIntervencion.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldEstadoIntervencion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldEstadoIntervencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 210, -1));

        jTextFieldTiempoAtencion.setEditable(false);
        jTextFieldTiempoAtencion.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldTiempoAtencion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldTiempoAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 210, -1));

        jTextFieldTiempoTotalAsignado.setEditable(false);
        jTextFieldTiempoTotalAsignado.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldTiempoTotalAsignado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldTiempoTotalAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 210, -1));

        jLabelCantTicketAsociadosAlGrupo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelCantTicketAsociadosAlGrupo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantTicketAsociadosAlGrupo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantTicketAsociadosAlGrupo.setText("Cantidad ticket asociado al grupo de resolución");
        getContentPane().add(jLabelCantTicketAsociadosAlGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        jLabelConstanteC.setBackground(new java.awt.Color(191, 185, 185));
        jLabelConstanteC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConstanteC.setForeground(new java.awt.Color(51, 153, 255));
        jLabelConstanteC.setText("C");
        getContentPane().add(jLabelConstanteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCU1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButton1AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Anterior;
    private javax.swing.JButton jButton1Siguiente;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1De;
    private javax.swing.JLabel jLabel1UNO;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelCantTicketAsociadosAlGrupo;
    private javax.swing.JLabel jLabelClasificacionActual;
    private javax.swing.JLabel jLabelConstanteC;
    private javax.swing.JLabel jLabelDE;
    private javax.swing.JLabel jLabelEstadoIntervencion;
    private javax.swing.JLabel jLabelEstadoTicket;
    private javax.swing.JLabel jLabelFechaApertura;
    private javax.swing.JLabel jLabelFiltrosUtilizados;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGrafico;
    private javax.swing.JLabel jLabelInfoDelGrupoResolucion;
    private javax.swing.JLabel jLabelInfoDelTicketAsociadoAlGrupo;
    private javax.swing.JLabel jLabelNombreGrupoResol;
    private javax.swing.JLabel jLabelNroTicket;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelOpciones;
    private javax.swing.JLabel jLabelOrdenado;
    private javax.swing.JLabel jLabelTiempoRealAtencion;
    private javax.swing.JLabel jLabelTiempoTotalAsig;
    private javax.swing.JLabel jLabelUNO;
    private javax.swing.JLabel jLabelVisualizando;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldClasificaciónTicket;
    private javax.swing.JTextField jTextFieldEstadoActualTicket;
    private javax.swing.JTextField jTextFieldEstadoIntervencion;
    private javax.swing.JTextField jTextFieldFechaApertura;
    private javax.swing.JTextField jTextFieldNombreGrupoResolución;
    private javax.swing.JTextField jTextFieldNroTicket;
    private javax.swing.JTextField jTextFieldTiempoAtencion;
    private javax.swing.JTextField jTextFieldTiempoTotalAsignado;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
