/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Marcos
 */
public class Caso_de_uso_24 extends javax.swing.JFrame {

    /**
     * Creates new form CasoDeUso24
     */
    public Caso_de_uso_24() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpciones = new javax.swing.JLabel();
        jLabelFiltros = new javax.swing.JLabel();
        jLabelOrdenado = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonAnteior = new javax.swing.JButton();
        jLabelVisualizando = new javax.swing.JLabel();
        jLabelUNO = new javax.swing.JLabel();
        jLabelDe = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelClasificacion = new javax.swing.JLabel();
        jLabelCantTicket = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelTicketAsociados = new javax.swing.JLabel();
        jLabel1UNO = new javax.swing.JLabel();
        jLabel1De = new javax.swing.JLabel();
        jLabel1C = new javax.swing.JLabel();
        jButton1Anterior = new javax.swing.JButton();
        jButton1Siguiente = new javax.swing.JButton();
        jLabelNroTicket = new javax.swing.JLabel();
        jLabelLegajo = new javax.swing.JLabel();
        jLabelEstadoActual = new javax.swing.JLabel();
        jLabelFechaApertura = new javax.swing.JLabel();
        jLabelUltimoGrpo = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPaneOrdenamientoPorDefecto = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPaneNuevoOrdenamiento = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPaneFiltrosUtilizados = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextFieldClasificacion = new javax.swing.JTextField();
        jTextFieldClasificacion1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCantTicketAsociadosAClasificacion = new javax.swing.JLabel();
        jTextFieldNroTicketPorPantalla = new javax.swing.JTextField();
        jTextFieldLegajoPorPantalla = new javax.swing.JTextField();
        jTextFieldEstadoActualPorPantalla = new javax.swing.JTextField();
        jTextFieldFechaAperturaPorPantalla = new javax.swing.JTextField();
        jTextFieldUltimoGpoResolPorPantalla = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información por clasificación actual del ticket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOpciones.setBackground(new java.awt.Color(191, 185, 185));
        jLabelOpciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpciones.setText("Opciones de ordenamiento");
        getContentPane().add(jLabelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabelFiltros.setBackground(new java.awt.Color(191, 185, 185));
        jLabelFiltros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFiltros.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFiltros.setText("Filtros utilizados");
        getContentPane().add(jLabelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jLabelOrdenado.setBackground(new java.awt.Color(191, 185, 185));
        jLabelOrdenado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOrdenado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrdenado.setText("Ordenado");
        getContentPane().add(jLabelOrdenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 30));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(191, 185, 185));
        jTextField2.setText("XXXXXXXXXX");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 270, 30));

        jButtonAnteior.setBackground(new java.awt.Color(191, 185, 185));
        jButtonAnteior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAnteior.setText("Anterior");
        getContentPane().add(jButtonAnteior, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabelVisualizando.setBackground(new java.awt.Color(191, 185, 185));
        jLabelVisualizando.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVisualizando.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVisualizando.setText("Visualizando");
        getContentPane().add(jLabelVisualizando, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 30));

        jLabelUNO.setBackground(new java.awt.Color(191, 185, 185));
        jLabelUNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUNO.setForeground(new java.awt.Color(51, 153, 255));
        jLabelUNO.setText("1");
        getContentPane().add(jLabelUNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 30));

        jLabelDe.setBackground(new java.awt.Color(191, 185, 185));
        jLabelDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDe.setText("de");
        getContentPane().add(jLabelDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, 30));

        jLabelX.setBackground(new java.awt.Color(191, 185, 185));
        jLabelX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelX.setForeground(new java.awt.Color(51, 153, 255));
        jLabelX.setText("X");
        getContentPane().add(jLabelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, 30));

        jButtonSiguiente.setBackground(new java.awt.Color(191, 185, 185));
        jButtonSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1060, 10));

        jLabelClasificacion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelClasificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClasificacion.setText("Clasificación");
        getContentPane().add(jLabelClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabelCantTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabelCantTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantTicket.setForeground(new java.awt.Color(246, 58, 58));
        jLabelCantTicket.setText("Información del ticket asociado a la clasificación: ");
        getContentPane().add(jLabelCantTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabelC.setBackground(new java.awt.Color(191, 185, 185));
        jLabelC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(51, 153, 255));
        jLabelC.setText("C");
        getContentPane().add(jLabelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, 60));

        jLabelTicketAsociados.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTicketAsociados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTicketAsociados.setForeground(new java.awt.Color(246, 58, 58));
        jLabelTicketAsociados.setText("Información asociada a la clasificación:");
        getContentPane().add(jLabelTicketAsociados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel1UNO.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1UNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1UNO.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1UNO.setText("1");
        getContentPane().add(jLabel1UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, -1, 40));

        jLabel1De.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1De.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1De.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1De.setText("de");
        getContentPane().add(jLabel1De, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        jLabel1C.setBackground(new java.awt.Color(191, 185, 185));
        jLabel1C.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1C.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1C.setText("C");
        getContentPane().add(jLabel1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, 40));

        jButton1Anterior.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Anterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1Anterior.setText("Anterior");
        getContentPane().add(jButton1Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jButton1Siguiente.setBackground(new java.awt.Color(191, 185, 185));
        jButton1Siguiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1Siguiente.setText("Siguiente");
        jButton1Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, -1));

        jLabelNroTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabelNroTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNroTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNroTicket.setText("Nro. Ticket");
        getContentPane().add(jLabelNroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabelLegajo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelLegajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLegajo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLegajo.setText("Nro. Legajo");
        getContentPane().add(jLabelLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabelEstadoActual.setBackground(new java.awt.Color(191, 185, 185));
        jLabelEstadoActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstadoActual.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoActual.setText("Estado actual del ticket");
        getContentPane().add(jLabelEstadoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabelFechaApertura.setBackground(new java.awt.Color(191, 185, 185));
        jLabelFechaApertura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaApertura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaApertura.setText("Fecha de apertura");
        getContentPane().add(jLabelFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabelUltimoGrpo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelUltimoGrpo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUltimoGrpo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUltimoGrpo.setText("Último grupo de resolución");
        getContentPane().add(jLabelUltimoGrpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jButtonImprimir.setBackground(new java.awt.Color(191, 185, 185));
        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, 120, 40));

        jButtonCancelar.setBackground(new java.awt.Color(191, 185, 185));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 120, 40));

        jTable1.setBackground(new java.awt.Color(191, 185, 185));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nro. Ticket"},
                {"Legajo"},
                {"Estado actual del ticket"},
                {"Fecha apertura"},
                {"Grupo actual de resolución"}
            },
            new String [] {
                "Ordenamiento por defecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(75, 102));
        jScrollPaneOrdenamientoPorDefecto.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPaneOrdenamientoPorDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 250, 110));

        jTable2.setBackground(new java.awt.Color(191, 185, 185));
        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 - NULL"},
                {"2 - NULL"},
                {"3 - NULL"},
                {"4 - NULL"},
                {"5 - NULL"}
            },
            new String [] {
                "Nuevo ordenamiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(75, 102));
        jScrollPaneNuevoOrdenamiento.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPaneNuevoOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 250, 110));

        jTable3.setBackground(new java.awt.Color(191, 185, 185));
        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"XXXXXXXXXX", "XXXXXXXXXX"},
                {"XXXXXXXXXX", "XXXXXXXXXX"},
                {"XXXXXXXXXX", "XXXXXXXXXX"},
                {"XXXXXXXXXX", "xxxxxxxxxx"}
            },
            new String [] {
                "Filtros", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setPreferredSize(new java.awt.Dimension(160, 151));
        jTable3.setRowHeight(23);
        jScrollPaneFiltrosUtilizados.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPaneFiltrosUtilizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 50));

        jTextFieldClasificacion.setEditable(false);
        jTextFieldClasificacion.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldClasificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldClasificacion.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 230, -1));

        jTextFieldClasificacion1.setEditable(false);
        jTextFieldClasificacion1.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldClasificacion1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldClasificacion1.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldClasificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 230, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1060, 10));

        jLabelCantTicketAsociadosAClasificacion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelCantTicketAsociadosAClasificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantTicketAsociadosAClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantTicketAsociadosAClasificacion.setText("Cantidad de ticket asociados a la clasificacion");
        getContentPane().add(jLabelCantTicketAsociadosAClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jTextFieldNroTicketPorPantalla.setEditable(false);
        jTextFieldNroTicketPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldNroTicketPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNroTicketPorPantalla.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldNroTicketPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 180, -1));

        jTextFieldLegajoPorPantalla.setEditable(false);
        jTextFieldLegajoPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldLegajoPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldLegajoPorPantalla.setText("XXXXXXXXXX");
        jTextFieldLegajoPorPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLegajoPorPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLegajoPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 180, -1));

        jTextFieldEstadoActualPorPantalla.setEditable(false);
        jTextFieldEstadoActualPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldEstadoActualPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEstadoActualPorPantalla.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldEstadoActualPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 180, -1));

        jTextFieldFechaAperturaPorPantalla.setEditable(false);
        jTextFieldFechaAperturaPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldFechaAperturaPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFechaAperturaPorPantalla.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldFechaAperturaPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 180, -1));

        jTextFieldUltimoGpoResolPorPantalla.setEditable(false);
        jTextFieldUltimoGpoResolPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldUltimoGpoResolPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUltimoGpoResolPorPantalla.setText("XXXXXXXXXX");
        getContentPane().add(jTextFieldUltimoGpoResolPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 790, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCU1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SiguienteActionPerformed

    private void jTextFieldLegajoPorPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLegajoPorPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLegajoPorPantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_24().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Anterior;
    private javax.swing.JButton jButton1Siguiente;
    private javax.swing.JButton jButtonAnteior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1C;
    private javax.swing.JLabel jLabel1De;
    private javax.swing.JLabel jLabel1UNO;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelCantTicket;
    private javax.swing.JLabel jLabelCantTicketAsociadosAClasificacion;
    private javax.swing.JLabel jLabelClasificacion;
    private javax.swing.JLabel jLabelDe;
    private javax.swing.JLabel jLabelEstadoActual;
    private javax.swing.JLabel jLabelFechaApertura;
    private javax.swing.JLabel jLabelFiltros;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLegajo;
    private javax.swing.JLabel jLabelNroTicket;
    private javax.swing.JLabel jLabelOpciones;
    private javax.swing.JLabel jLabelOrdenado;
    private javax.swing.JLabel jLabelTicketAsociados;
    private javax.swing.JLabel jLabelUNO;
    private javax.swing.JLabel jLabelUltimoGrpo;
    private javax.swing.JLabel jLabelVisualizando;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JScrollPane jScrollPaneFiltrosUtilizados;
    private javax.swing.JScrollPane jScrollPaneNuevoOrdenamiento;
    private javax.swing.JScrollPane jScrollPaneOrdenamientoPorDefecto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldClasificacion;
    private javax.swing.JTextField jTextFieldClasificacion1;
    private javax.swing.JTextField jTextFieldEstadoActualPorPantalla;
    private javax.swing.JTextField jTextFieldFechaAperturaPorPantalla;
    private javax.swing.JTextField jTextFieldLegajoPorPantalla;
    private javax.swing.JTextField jTextFieldNroTicketPorPantalla;
    private javax.swing.JTextField jTextFieldUltimoGpoResolPorPantalla;
    // End of variables declaration//GEN-END:variables
}
