/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class Caso_de_uso_12 extends javax.swing.JFrame {

    /**
     * Creates new form Caso_de_uso_12
     */
    public Caso_de_uso_12() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCodigoNumerico = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelListaGrupoResolucion = new javax.swing.JLabel();
        jTextFieldCodigoNumerico = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jComboBoxNombre = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGruposAsignar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGruposAsignados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabelLogoFondo = new javax.swing.JLabel();
        jButtonAsignar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar clasificacion de ticket");
        setMinimumSize(new java.awt.Dimension(1025, 635));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTitulo.setFont(new java.awt.Font("MS PGothic", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(45, 93, 165));
        jLabelTitulo.setText("La llamita");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 200, 50));

        jLabelCodigoNumerico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCodigoNumerico.setText("Código numérico: ");
        getContentPane().add(jLabelCodigoNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre: ");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDescripcion.setText("Descripción:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstado.setText("Estado:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelListaGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelListaGrupoResolucion.setText("Lista grupos de resolución:");
        getContentPane().add(jLabelListaGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextFieldCodigoNumerico.setEditable(false);
        jTextFieldCodigoNumerico.setBackground(new java.awt.Color(227, 227, 227));
        jTextFieldCodigoNumerico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCodigoNumerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoNumericoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigoNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 180, 30));

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 210, 30));

        jComboBoxNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 390, 30));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 120, 40));

        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 120, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPaneDescripcion.setViewportView(jTextArea2);

        getContentPane().add(jScrollPaneDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 400, 170));

        jTableGruposAsignar.setBackground(new java.awt.Color(204, 255, 255));
        jTableGruposAsignar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Administradosr de Bases de Datos"},
                {"Administrador Proxy y correo electronico"},
                {"Administrador SUSE Linux  "},
                {"Comunicaciones "},
                {"Desarrollo Sistema Comercial"},
                {"Redes LAN "}
            },
            new String [] {
                "Grupos a asignar"
            }
        ));
        jTableGruposAsignar.setGridColor(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jTableGruposAsignar);
        if (jTableGruposAsignar.getColumnModel().getColumnCount() > 0) {
            jTableGruposAsignar.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 320, 120));

        jTableGruposAsignados.setBackground(new java.awt.Color(204, 255, 255));
        jTableGruposAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Grupos asignados"
            }
        ));
        jTableGruposAsignados.setGridColor(new java.awt.Color(51, 153, 255));
        jScrollPane2.setViewportView(jTableGruposAsignados);
        if (jTableGruposAsignados.getColumnModel().getColumnCount() > 0) {
            jTableGruposAsignados.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 320, 120));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("<>");
        jButton2.setActionCommand("<>");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 70, 40));

        jLabelLogoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logofondo_GrupoResolucion.png"))); // NOI18N
        getContentPane().add(jLabelLogoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 400));

        jButtonAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-grupoResolucion.jpg"))); // NOI18N
        getContentPane().add(jButtonAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoNumericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoNumericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoNumericoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jButtonAsignar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxNombre;
    private javax.swing.JLabel jLabelCodigoNumerico;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelListaGrupoResolucion;
    private javax.swing.JLabel jLabelLogoFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JTable jTableGruposAsignados;
    private javax.swing.JTable jTableGruposAsignar;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldCodigoNumerico;
    // End of variables declaration//GEN-END:variables
}
