/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class Caso_de_uso_11 extends javax.swing.JFrame {

    /**
     * Creates new form Caso_de_uso_11
     */
    public Caso_de_uso_11() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo.png")).getImage());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigoNumerico = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelGrupoResolucion = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldCodigoNumerico = new javax.swing.JTextField();
        jTextFieldNobre = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jComboBoxGrupoResolucion = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPaneBusqueda = new javax.swing.JScrollPane();
        jTableBusqueda = new javax.swing.JTable();
        jScrollPaneDetallesCadaClasificacion = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldCantidadDeTicketsCerrados = new javax.swing.JTextField();
        jLabelCantidadDeTicketsCerrados = new javax.swing.JLabel();
        jLabelCantidadDeTicketsAbiertos = new javax.swing.JLabel();
        jTextFieldCantidadDeTicketsAbiertos = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonModificarClasificacion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelLogoFondo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar clasificacion de tickets");
        setMinimumSize(new java.awt.Dimension(1025, 635));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodigoNumerico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCodigoNumerico.setText("Codigo Numérico: ");
        getContentPane().add(jLabelCodigoNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Parte del nombre: ");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDescripcion.setText("Parte de la descripcion:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGrupoResolucion.setText("Grupo de resolución:");
        getContentPane().add(jLabelGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstado.setText("Estado:");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));
        getContentPane().add(jTextFieldCodigoNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 240, 30));
        getContentPane().add(jTextFieldNobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 240, 30));

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 340, 30));

        jComboBoxGrupoResolucion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGrupoResolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxGrupoResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 290, 30));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 120, 40));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cerrar");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 160, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPaneDescripcion.setViewportView(jTextArea2);

        getContentPane().add(jScrollPaneDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 540, 100));

        jTableBusqueda.setBackground(new java.awt.Color(204, 255, 255));
        jTableBusqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código numérico", "Nombre completo", "Descripción completa", "Estado"
            }
        ));
        jTableBusqueda.setGridColor(new java.awt.Color(0, 204, 255));
        jScrollPaneBusqueda.setViewportView(jTableBusqueda);

        getContentPane().add(jScrollPaneBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1070, 120));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(227, 227, 227));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro. de ticket", "Legajo del usuario", "Apellido y nombre", "Teléfono interno", "Teléfono directo", "Fecha de derivación", "Hora de derivación", "Estado de la intervención"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPaneDetallesCadaClasificacion.setViewportView(jTable1);

        getContentPane().add(jScrollPaneDetallesCadaClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1070, 130));

        jTextFieldCantidadDeTicketsCerrados.setEditable(false);
        jTextFieldCantidadDeTicketsCerrados.setBackground(new java.awt.Color(227, 227, 227));
        jTextFieldCantidadDeTicketsCerrados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadDeTicketsCerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeTicketsCerradosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadDeTicketsCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 110, 30));

        jLabelCantidadDeTicketsCerrados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadDeTicketsCerrados.setText("Cantidad de tickets cerrados:");
        getContentPane().add(jLabelCantidadDeTicketsCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        jLabelCantidadDeTicketsAbiertos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCantidadDeTicketsAbiertos.setText("Cantidad de tickets abiertos:");
        getContentPane().add(jLabelCantidadDeTicketsAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jTextFieldCantidadDeTicketsAbiertos.setEditable(false);
        jTextFieldCantidadDeTicketsAbiertos.setBackground(new java.awt.Color(227, 227, 227));
        jTextFieldCantidadDeTicketsAbiertos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadDeTicketsAbiertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadDeTicketsAbiertosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadDeTicketsAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 110, 30));

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 160, 40));

        jButtonModificarClasificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificarClasificacion.setText("Modificar clasificacion");
        getContentPane().add(jButtonModificarClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, 160, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1080, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 448, 1080, 10));

        jLabelLogoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logofondo_GrupoResolucion.png"))); // NOI18N
        getContentPane().add(jLabelLogoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 400));

        jLabelTitulo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTitulo.setFont(new java.awt.Font("MS PGothic", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(45, 93, 165));
        jLabelTitulo.setText("La llamita");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 200, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-grupoResolucion.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadDeTicketsCerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeTicketsCerradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeTicketsCerradosActionPerformed

    private void jTextFieldCantidadDeTicketsAbiertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadDeTicketsAbiertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadDeTicketsAbiertosActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_de_uso_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_de_uso_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificarClasificacion;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxGrupoResolucion;
    private javax.swing.JLabel jLabelCantidadDeTicketsAbiertos;
    private javax.swing.JLabel jLabelCantidadDeTicketsCerrados;
    private javax.swing.JLabel jLabelCodigoNumerico;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGrupoResolucion;
    private javax.swing.JLabel jLabelLogoFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPaneBusqueda;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JScrollPane jScrollPaneDetallesCadaClasificacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableBusqueda;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldCantidadDeTicketsAbiertos;
    private javax.swing.JTextField jTextFieldCantidadDeTicketsCerrados;
    private javax.swing.JTextField jTextFieldCodigoNumerico;
    private javax.swing.JTextField jTextFieldNobre;
    // End of variables declaration//GEN-END:variables
}
