/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Marcos
 */
public class VerDetalleTicket extends javax.swing.JFrame {

    /**
     * Creates new form PantallaVERDETALLETICKET
     */
    public VerDetalleTicket() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInformacionDelUsuarioQueReclamo = new javax.swing.JLabel();
        jLabelNroLegajo = new javax.swing.JLabel();
        jLabelApellidoyNombre = new javax.swing.JLabel();
        jLabelTelefonoInterno = new javax.swing.JLabel();
        jLabelTelefonoDirecto = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jLabelDescripcionDelCargo = new javax.swing.JLabel();
        jLabelInformacionHistoricoReclamo = new javax.swing.JLabel();
        jTextFieldNroLegajo = new javax.swing.JTextField();
        jTextFieldTelefonoInterno = new javax.swing.JTextField();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jTextFieldApeYNombre = new javax.swing.JTextField();
        jTextFieldTelefonoDirecto = new javax.swing.JTextField();
        jTextFieldDescrpDelCargo = new javax.swing.JTextField();
        jLabelObservaciones = new javax.swing.JLabel();
        jScrollPaneObservaciones = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonCerrar = new javax.swing.JButton();
        jButton1CerrarTicket = new javax.swing.JButton();
        jButton1DerivarTicket = new javax.swing.JButton();
        jLabel2NroTicket = new javax.swing.JLabel();
        jTextField1NroTicketPorPantalla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalle del ticket");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInformacionDelUsuarioQueReclamo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelInformacionDelUsuarioQueReclamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInformacionDelUsuarioQueReclamo.setForeground(new java.awt.Color(246, 58, 58));
        jLabelInformacionDelUsuarioQueReclamo.setText("Información del usuario que realizó el reclamo: ");
        getContentPane().add(jLabelInformacionDelUsuarioQueReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLabelNroLegajo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelNroLegajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNroLegajo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNroLegajo.setText("Nro. legajo");
        getContentPane().add(jLabelNroLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabelApellidoyNombre.setBackground(new java.awt.Color(191, 185, 185));
        jLabelApellidoyNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApellidoyNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidoyNombre.setText("Apellido y Nombre");
        getContentPane().add(jLabelApellidoyNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabelTelefonoInterno.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTelefonoInterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefonoInterno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoInterno.setText("Teléfono interno");
        getContentPane().add(jLabelTelefonoInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabelTelefonoDirecto.setBackground(new java.awt.Color(191, 185, 185));
        jLabelTelefonoDirecto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefonoDirecto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoDirecto.setText("Teléfono directo");
        getContentPane().add(jLabelTelefonoDirecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLabelUbicacion.setBackground(new java.awt.Color(191, 185, 185));
        jLabelUbicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUbicacion.setText("Ubicación");
        getContentPane().add(jLabelUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabelDescripcionDelCargo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelDescripcionDelCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDescripcionDelCargo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcionDelCargo.setText("Descripción del cargo");
        getContentPane().add(jLabelDescripcionDelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabelInformacionHistoricoReclamo.setBackground(new java.awt.Color(191, 185, 185));
        jLabelInformacionHistoricoReclamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInformacionHistoricoReclamo.setForeground(new java.awt.Color(246, 58, 58));
        jLabelInformacionHistoricoReclamo.setText("Información del histórico del reclamo:");
        getContentPane().add(jLabelInformacionHistoricoReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jTextFieldNroLegajo.setEditable(false);
        jTextFieldNroLegajo.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldNroLegajo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldNroLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 240, -1));

        jTextFieldTelefonoInterno.setEditable(false);
        jTextFieldTelefonoInterno.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldTelefonoInterno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldTelefonoInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 240, -1));

        jTextFieldUbicacion.setEditable(false);
        jTextFieldUbicacion.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldUbicacion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 780, -1));

        jTextFieldApeYNombre.setEditable(false);
        jTextFieldApeYNombre.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldApeYNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldApeYNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 330, -1));

        jTextFieldTelefonoDirecto.setEditable(false);
        jTextFieldTelefonoDirecto.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldTelefonoDirecto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldTelefonoDirecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 330, -1));

        jTextFieldDescrpDelCargo.setEditable(false);
        jTextFieldDescrpDelCargo.setBackground(new java.awt.Color(191, 185, 185));
        jTextFieldDescrpDelCargo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldDescrpDelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 330, -1));

        jLabelObservaciones.setBackground(new java.awt.Color(191, 185, 185));
        jLabelObservaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservaciones.setText("Observaciones");
        getContentPane().add(jLabelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(191, 185, 185));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneObservaciones.setViewportView(jTextArea1);

        getContentPane().add(jScrollPaneObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 800, 100));

        jButtonCerrar.setBackground(new java.awt.Color(191, 185, 185));
        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 120, 40));

        jButton1CerrarTicket.setBackground(new java.awt.Color(191, 185, 185));
        jButton1CerrarTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1CerrarTicket.setText("Cerrar ticket");
        getContentPane().add(jButton1CerrarTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 120, 40));

        jButton1DerivarTicket.setBackground(new java.awt.Color(191, 185, 185));
        jButton1DerivarTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1DerivarTicket.setText("Derivar ticket ");
        getContentPane().add(jButton1DerivarTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 120, 40));

        jLabel2NroTicket.setBackground(new java.awt.Color(191, 185, 185));
        jLabel2NroTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2NroTicket.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2NroTicket.setText("Nro. Ticket: ");
        getContentPane().add(jLabel2NroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jTextField1NroTicketPorPantalla.setEditable(false);
        jTextField1NroTicketPorPantalla.setBackground(new java.awt.Color(191, 185, 185));
        jTextField1NroTicketPorPantalla.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextField1NroTicketPorPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, -1));

        jTable1.setBackground(new java.awt.Color(191, 185, 185));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha cambio de estado", "Hora cambio de estado", "Operador interventor", "Grupo resolución", "Clasificación del ticket", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 950, 140));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoCU1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDetalleTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDetalleTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDetalleTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDetalleTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDetalleTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CerrarTicket;
    private javax.swing.JButton jButton1DerivarTicket;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel2NroTicket;
    private javax.swing.JLabel jLabelApellidoyNombre;
    private javax.swing.JLabel jLabelDescripcionDelCargo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInformacionDelUsuarioQueReclamo;
    private javax.swing.JLabel jLabelInformacionHistoricoReclamo;
    private javax.swing.JLabel jLabelNroLegajo;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelTelefonoDirecto;
    private javax.swing.JLabel jLabelTelefonoInterno;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneObservaciones;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1NroTicketPorPantalla;
    private javax.swing.JTextField jTextFieldApeYNombre;
    private javax.swing.JTextField jTextFieldDescrpDelCargo;
    private javax.swing.JTextField jTextFieldNroLegajo;
    private javax.swing.JTextField jTextFieldTelefonoDirecto;
    private javax.swing.JTextField jTextFieldTelefonoInterno;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables
}
