package com.postgres.db;
// Generated 03/10/2018 11:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historialintervencion generated by hbm2java
 */
public class Historialintervencion  implements java.io.Serializable {


     private int idHistorialIntervencion;
     private Intervencion intervencion;
     private String estado;
     private Date fechainicio;
     private Date fechafin;
     private Date horainicio;
     private Date horafin;

    public Historialintervencion() {
    }

    public Historialintervencion(int idHistorialIntervencion, Intervencion intervencion, String estado, Date fechainicio, Date fechafin, Date horainicio, Date horafin) {
       this.idHistorialIntervencion = idHistorialIntervencion;
       this.intervencion = intervencion;
       this.estado = estado;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.horainicio = horainicio;
       this.horafin = horafin;
    }
   
    public int getIdHistorialIntervencion() {
        return this.idHistorialIntervencion;
    }
    
    public void setIdHistorialIntervencion(int idHistorialIntervencion) {
        this.idHistorialIntervencion = idHistorialIntervencion;
    }
    public Intervencion getIntervencion() {
        return this.intervencion;
    }
    
    public void setIntervencion(Intervencion intervencion) {
        this.intervencion = intervencion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }




}


