package com.postgres.db;
// Generated 03/10/2018 11:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hitorialticket generated by hbm2java
 */
public class Hitorialticket  implements java.io.Serializable {


     private int idHistorialTicket;
     private Ticket ticket;
     private Date fechainicio;
     private Date fechafin;
     private Date horainicio;
     private Date horafin;
     private String estado;

    public Hitorialticket() {
    }

    public Hitorialticket(int idHistorialTicket, Ticket ticket, Date fechainicio, Date fechafin, Date horainicio, Date horafin, String estado) {
       this.idHistorialTicket = idHistorialTicket;
       this.ticket = ticket;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.horainicio = horainicio;
       this.horafin = horafin;
       this.estado = estado;
    }
   
    public int getIdHistorialTicket() {
        return this.idHistorialTicket;
    }
    
    public void setIdHistorialTicket(int idHistorialTicket) {
        this.idHistorialTicket = idHistorialTicket;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Date getHorafin() {
        return this.horafin;
    }
    
    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


