package com.postgres.db;
// Generated 03/10/2018 11:33:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Observacion generated by hbm2java
 */
public class Observacion  implements java.io.Serializable {


     private int idObservacion;
     private Ticket ticket;
     private String observacion;
     private Date fechacreacion;
     private Date horacreacion;

    public Observacion() {
    }

    public Observacion(int idObservacion, Ticket ticket, String observacion, Date fechacreacion, Date horacreacion) {
       this.idObservacion = idObservacion;
       this.ticket = ticket;
       this.observacion = observacion;
       this.fechacreacion = fechacreacion;
       this.horacreacion = horacreacion;
    }
   
    public int getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(int idObservacion) {
        this.idObservacion = idObservacion;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Date getHoracreacion() {
        return this.horacreacion;
    }
    
    public void setHoracreacion(Date horacreacion) {
        this.horacreacion = horacreacion;
    }




}


