package com.postgres.db;
// Generated 03/10/2018 11:33:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int legajoUsuario;
     private String tipo;
     private String nombre;
     private String apellido;
     private Set empleados = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int legajoUsuario, String tipo, String nombre, String apellido) {
        this.legajoUsuario = legajoUsuario;
        this.tipo = tipo;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Usuario(int legajoUsuario, String tipo, String nombre, String apellido, Set empleados) {
       this.legajoUsuario = legajoUsuario;
       this.tipo = tipo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.empleados = empleados;
    }
   
    public int getLegajoUsuario() {
        return this.legajoUsuario;
    }
    
    public void setLegajoUsuario(int legajoUsuario) {
        this.legajoUsuario = legajoUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


